services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached

    env_file:
      - ../.env

    working_dir: /workspace

    ports:
      - "8501:8501"
      - "5173:5173"

    command: sleep infinity 